/* MODELAGEM CONCEITUAL */

CRIAR UMA TABELA - LIVRO

NOME DO LIVRO - CARACTER (30)
NOME DO AUTOR - CARACTER (30)
SEXO DO AUTOR - CARACTER (1)
NUMERO DE PAGINAS - NUMERICO (4)
NOME DA EDITORA - CARACTER (30)
VALOR DO LIVRO - NUMERICO (5)
UF DA EDITORA - CARACTER (2)
ANO DA PUBLICACAO - NUMERICO (4)

/* FISICA */

CREATE DATABASE LIVRARIA;

USE LIVRARIA;

CREATE TABLE LIVRO (
    NOME_DO_LIVRO VARCHAR (30),
    NOME_DO_AUTOR VARCHAR (30),
    SEXO CHAR (1),
    PAGINAS INT (4),
    NOME_DA_EDITORA VARCHAR (30),
    VALOR_DO_LIVRO CHAR (6),
    UF CHAR (2),
    ANO CHAR (4)
);

INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('CAVALEIRO REAL','ANA CLAUDIA','F','465','ATLAS','49,9','RJ','2009');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('SQL PARA LEIGOS','JOAO NUNES','M','450','ADDISON','98','SP','2018');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('RECEITAS CASEIRAS','CELIA TAVARES','F','210','ATLAS','45','RJ','2008');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('PESSOAS EFETIVAS','EDUARDO SANTOS','M','390','BETA','78,99','RJ','2018');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('HABITOS SAUDAVEIS','EDUARDO SANTOS','M','630','BETA','150,98','RJ','2019');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('A CASA MARROM','HERMES MACEDO','M','250','BUBBA','60','MG','2016');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('ESTACIO QUERIDO','GERALDO FRANCISCO','M','310','INSIGNIA','100','ES','2015');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('PRA SEMPRE AMIGAS','LEDA SILVA','F','510','INSIGNIA','78,98','ES','2011');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('COPAS INESQUECIVEIS','MARCO ALCANTARA','M','200','LARSON','130,98','RS','2018');
INSERT INTO LIVRO (NOME_DO_LIVRO, NOME_DO_AUTOR, SEXO, PAGINAS, NOME_DA_EDITORA, VALOR_DO_LIVRO, UF, ANO) VALUES ('O PODER DA MENTE','CLARA MAFRA','F','120','CONTINENTAL','56,58','SP','2017');

SELECT NOME_DO_LIVRO, NOME_DA_EDITORA FROM LIVRO;

SELECT NOME_DO_LIVRO, UF FROM LIVRO
WHERE SEXO = 'M';

SELECT NOME_DO_LIVRO, PAGINAS FROM LIVRO
WHERE SEXO = 'F';

SELECT VALOR_DO_LIVRO FROM LIVRO
WHERE UF = 'SP';

SELECT SEXO FROM LIVRO
WHERE SEXO = 'M' AND UF = 'SP,RJ';

SELECT SEXO FROM LIVRO
WHERE SEXO = 'M' AND WHERE UF LIKE 'SP, RJ';


SELECT NOME_DO_LIVRO AS LIVRO, NOME_DO_AUTOR AS AUTOR, ANO, UF FROM LIVRO
WHERE SEXO ='F' AND UF = 'RJ';

SELECT NOME_DO_LIVRO AS LIVRO, NOME_DO_AUTOR AS AUTOR, ANO, UF FROM LIVRO
WHERE SEXO ='F' OR UF = 'RJ';

SELECT NOME_DO_AUTOR, UF FROM LIVRO
WHERE SEXO ='M' AND UF = 'RJ' OR UF ='SP';

SELECT COUNT(*) AS "QUANTIDADE DE REGISTROS DA TAB CLIENTE" FROM LIVRO;

SELECT SEXO, COUNT(8) FROM LIVRO
GROUP BY SEXO;

SELECT COUNT(*) AS REGISTROS FROM LIVRO;

SELECT NOME_DO_AUTOR, COUNT(*) AS REGISTROS FROM LIVRO
WHERE SEXO ='M'
GROUP BY NOME_DO_AUTOR;

SELECT NOME_DO_LIVRO, UF, COUNT(*) AS REGISTROS FROM LIVRO
GROUP BY UF;





