/* Modelagem Básica - ENTIDADE = TABELA */

CLIENTE 

NOME - CARACTER (30)
CPF - NUMERICO (11)
EMAIL - CARACTER (30)
TELEFONE - CARACTER (30)
ENDERECO - CARACTER (100)
SEXO - CARACTER (1)

/* PROCESSOS DE MODELAGEM */

/* FASE 1 E FASE 2 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL
MODELAGEM LÓGICA 

/* FASE 3 - DBA / AD */
MODELAGEM FÍSICA

/* CRIANDO BANCO DE DADOS*/

CREATE DATABASE PROJETO;

/* CONECTANDO-SE A UM BANCO */

USE PROJETO;

/* CRIANDO TABELA */

CREATE TABLE CLIENTE (
	IDCLIENTE INTEGER,
    NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF CHAR (11),
	TELEFONE VARCHAR (30),
	ENDERECO VARCHAR (100)
	
);

/* VERIFICANDO TABELAS */

SHOW TABLES;
 
 /* DESCOBRINDO A ESTRUTURA DE UMA TABELA */
 
DESC CLIENTE;
 
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES('JOAO', 'M', 'JOAO@gmail.com', 67086101916, '(45) 922923110', 'MAIA LACERDA - RJ');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES('MARIA', 'F', 'MARIA@gmail.com', 12667186994, '(45) 922990110', 'MANOEL RIBAS - PR');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES('CLEBER', 'M', 'CLEBEER@gmail.com', 78746183945, '(45) 922994710', 'RUA PARANA - PR');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES('JOSE', 'M', 'JOSE@gmail.com', 78746183954, '(45) 987994710', 'BARRA DA TIJUCA - RJ');
INSERT INTO CLIENTE (NOME, SEXO, EMAIL, CPF, TELEFONE, ENDERECO) VALUES('FERNANDA', 'F', 'FERNANDA@gmail.com', 48746183954, '(45) 987912710', 'CANCELLI - PR');


INSERT INTO CLIENTE VALUES(1,'JOAO','M','JOAO@GMAIL.COM',988638273,'22923110','MAIA LACERDA - ESTACIO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES(2,'CELIA','F','CELIA@GMAIL.COM',541521456,'25078869','RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
INSERT INTO CLIENTE VALUES(3,'JORGE','M',NULL,885755896,'58748895','OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES(4,'LILIAN','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','947785696',887774856);
INSERT INTO CLIENTE VALUES(5,'ANA','F','ANA@GLOBO.COM',85548962,'548556985','PRES ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
                          (6,'CARLA','F','CARLA@TERATI.COM.BR',7745828,'66587458','SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');		  
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES(7,'CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',99999999);
INSERT INTO CLIENTE(IDCLIENTE,NOME,SEXO,ENDERECO,TELEFONE,CPF) VALUES(8,'CLARA','F','SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ','883665843',22222222);



SELECT NOME, SEXO, EMAIL, CPF, TELEFONE, ENDEREÇO FROM CLIENTE;
SELECT NOW() AS DATAEHORA, NOME AS CLIENTE, CPF FROM CLIENTE;
SELECT NOW() AS DATAEHORA, 'GABRIEL ALVISE' AS RESPONSAVEL_PELOS_CLIENTES, NOME AS CLIENTES, CPF, TELEFONE FROM CLIENTE;

SELECT * FROM CLIENTE;

SELECT NOME, SEXO, ENDERECO, CPF, TELEFONE, EMAIL, NOW() AS DATAEHORA FROM CLIENTE;

SELECT NOME AS CLIENTES, ENDERECO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME AS CLIENTE FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME AS CLIENTE, CPF, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME AS CLIENTES, CPF, EMAIL, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%PR';

DROP TABLE CLIENTE;
DROP DATABASE PROJETO;

SELECT NOME AS CLIENTES, CPF, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME AS CLIENTES, CPF, ENDERECO FROM CLIENTE
WHERE SEXO ='F' AND ENDERECO LIKE '%PR';

SELECT NOME AS CLIENTES, CPF, ENDERECO FROM CLIENTE
WHERE SEXO ='F' OR ENDERECO LIKE '%PR';

SELECT ENDERECO, COUNT(*) FROM CLIENTE
GROUP BY ENDERECO;

UPDATE CLIENTE
SET TELEFONE ='(45) 999417862'
WHERE NOME='JOAO';

UPDATE CLIENTE
SET CPF ='12667186997'
WHERE NOME='JOSE';

UPDATE CLIENTE
SET EMAIL='CLARA@GMAIL.COM'
WHERE IDCLIENTE='7';

UPDATE CLIENTE
SET EMAIL='CLARA@HOTMAIL.COM'
WHERE IDCLIENTE='8';

UPDATE CLIENTE
SET EMAIL='JORGE@GMAIL.COM'
WHERE IDCLIENTE='3';

UPDATE CLIENTE
SET EMAIL='LILIAN@HOTMAIL.COM'
WHERE IDCLIENTE='4';

UPDATE CLIENTE
SET EMAIL='JOAO@GMAIL.COM'
WHERE IDCLIENTE='1';

SELECT NOME FROM CLIENTE
WHERE EMAIL='NULL';